export const MYBRICKS_PREFIXCLS = "mb";

export const SYSTEM_VARIABLE_NAME_MAP = {
  [`--${MYBRICKS_PREFIXCLS}-color-primary`]: "品牌色",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-bg`]: "主色浅色背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-bg-hover`]: "主色浅色背景悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-border`]: "主色描边色",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-border-hover`]: "主色描边色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-hover`]: "主色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-active`]: "主色激活态",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-text-hover`]: "主色文本悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-text`]: "主色文本",
  [`--${MYBRICKS_PREFIXCLS}-color-primary-text-active`]: "主色文本激活态",

  [`--${MYBRICKS_PREFIXCLS}-color-error`]: "错误色",
  [`--${MYBRICKS_PREFIXCLS}-color-error-bg`]: "错误色的浅色背景颜色",
  [`--${MYBRICKS_PREFIXCLS}-color-error-bg-hover`]: "错误色的浅色背景色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-border`]: "错误色的描边色",
  [`--${MYBRICKS_PREFIXCLS}-color-error-border-hover`]: "错误色的描边色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-hover`]: "错误色的深色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-active`]: "错误色的深色激活态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-text-hover`]: "错误色的文本悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-text`]: "错误色的文本默认态",
  [`--${MYBRICKS_PREFIXCLS}-color-error-text-active`]: "错误色的文本激活态",

  [`--${MYBRICKS_PREFIXCLS}-color-warning`]: "警戒色",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-bg`]: "警戒色的浅色背景颜色",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-bg-hover`]: "警戒色的浅色背景色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-border`]: "警戒色的描边色",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-border-hover`]: "警戒色的描边色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-hover`]: "警戒色的深色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-active`]: "警戒色的深色激活态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-text-hover`]: "警戒色的文本悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-text`]: "警戒色的文本默认态",
  [`--${MYBRICKS_PREFIXCLS}-color-warning-text-active`]: "警戒色的文本激活态",

  [`--${MYBRICKS_PREFIXCLS}-color-success`]: "成功色",
  [`--${MYBRICKS_PREFIXCLS}-color-success-bg`]: "成功色的浅色背景颜色",
  [`--${MYBRICKS_PREFIXCLS}-color-success-bg-hover`]: "成功色的浅色背景色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-border`]: "成功色的描边色",
  [`--${MYBRICKS_PREFIXCLS}-color-success-border-hover`]: "成功色的描边色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-hover`]: "成功色的深色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-active`]: "成功色的深色激活态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-text-hover`]: "成功色的文本悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-text`]: "成功色的文本默认态",
  [`--${MYBRICKS_PREFIXCLS}-color-success-text-active`]: "成功色的文本激活态",

  [`--${MYBRICKS_PREFIXCLS}-color-info`]: "信息色",
  [`--${MYBRICKS_PREFIXCLS}-color-info-bg`]: "信息色的浅色背景颜色",
  [`--${MYBRICKS_PREFIXCLS}-color-info-bg-hover`]: "信息色的浅色背景色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-border`]: "信息色的描边色",
  [`--${MYBRICKS_PREFIXCLS}-color-info-border-hover`]: "信息色的描边色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-hover`]: "信息色的深色悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-active`]: "信息色的深色激活态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-text-hover`]: "信息色的文本悬浮态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-text`]: "信息色的文本默认态",
  [`--${MYBRICKS_PREFIXCLS}-color-info-text-active`]: "信息色的文本激活态",

  [`--${MYBRICKS_PREFIXCLS}-color-link`]: "链接色",
  [`--${MYBRICKS_PREFIXCLS}-color-link-hover`]: "超链接悬浮颜色",
  [`--${MYBRICKS_PREFIXCLS}-color-link-active`]: "超链接激活颜色",

  [`--${MYBRICKS_PREFIXCLS}-color-text-base`]: "基础文本色",
  [`--${MYBRICKS_PREFIXCLS}-color-text`]: "一级文本色",
  [`--${MYBRICKS_PREFIXCLS}-color-text-secondary`]: "二级文本色",
  [`--${MYBRICKS_PREFIXCLS}-color-text-tertiary`]: "三级文本色",
  [`--${MYBRICKS_PREFIXCLS}-color-text-quaternary`]: "四级文本色",

  [`--${MYBRICKS_PREFIXCLS}-color-bg-base`]: "基础背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-bg-container`]: "组件容器背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-bg-elevated`]: "浮层容器背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-bg-layout`]: "布局背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-bg-spotlight`]: "引起注意的背景色",
  [`--${MYBRICKS_PREFIXCLS}-color-bg-mask`]: "浮层的背景蒙层颜色",

  [`--${MYBRICKS_PREFIXCLS}-color-border`]: "一级边框色",
  [`--${MYBRICKS_PREFIXCLS}-color-border-secondary`]: "二级边框色",

  [`--${MYBRICKS_PREFIXCLS}-color-fill`]: "一级填充色",
  [`--${MYBRICKS_PREFIXCLS}-color-fill-secondary`]: "二级填充色",
  [`--${MYBRICKS_PREFIXCLS}-color-fill-tertiary`]: "三级填充色",
  [`--${MYBRICKS_PREFIXCLS}-color-fill-quaternary`]: "四级填充色",
}

export const PRESET_COLORS = [
  "#1677FF",
  "#722ED1",
  "#13C2C2",
  "#52C41A",
  "#EB2F96",
  "#F5222D",
  "#FA8C16",
  "#FADB14",
  "#FA541C",
  "#2F54EB",
  "#FAAD14",
  "#A0D911",
  "#000"
]
